version: 2

updates:
  - package-ecosystem: npm
    directory: /.github/actions/config-resolver
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Madrid
    open-pull-requests-limit: 5
    labels:
      - kind/internal

  - package-ecosystem: npm
    directory: /docs
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Madrid
    open-pull-requests-limit: 5
    labels:
      - kind/internal

  - package-ecosystem: maven
    directory: /code
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Madrid
    open-pull-requests-limit: 5
    labels:
      - kind/internal

  - package-ecosystem: maven
    directory: /e2e/karate
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Madrid
    open-pull-requests-limit: 5
    labels:
      - kind/internal

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Madrid
    open-pull-requests-limit: 5
    labels:
      - kind/internal

  - package-ecosystem: docker-compose
    directory: /code/boot/src/test/resources/compose
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Madrid
    open-pull-requests-limit: 5
    labels:
      - kind/internal
