# docker-compose environment variables:  NA
# docker-compose folder structure:       mariadb/<DB_NAME>/scripts
jdbc-url: jdbc:mariadb://localhost:3306/KARATE
driver-class-name: org.mariadb.jdbc.Driver
username: karate
password: karate-pwd
health-query: SELECT 1 FROM DUAL
