= Karate Tools Release Notes

[cols="1,1,6"]
|===
| Version | Date | Description

| 5.1.0
| 2025-09-29
|

✔️ Karate Tools - Dependencies Update (artemis-jms-client 2.39.0 -> 2.42.0, assertj-core 3.27.2 -> 3.27.6, checkstyle 10.21.1 -> 11.0.1, com.github.spotbugs 4.8.6 -> 4.9.6, commons-io 2.18.0 -> 2.20.0, gson 2.11.0 -> 2.13.2, jackson 2.18.2 -> 2.20.0, jakarta.validation:jakarta.validation-api 3.1.0 -> 3.1.1, jsonwebtoken 0.12.6 -> 0.13.0, junit 5.11.4 -> 5.13.4, kafka-clients 3.9.0 -> 3.9.1, logback 1.5.16 -> 1.5.18, lombok 1.18.36 -> 1.18.42, mariadb-java-client 3.5.1 -> 3.5.6, maven-model 3.9.9 -> 3.9.11, mockito 5.15.2 -> 5.20.0, mongodb-driver-sync 5.3.0 -> 5.6.0, postgresql 42.7.4 -> 42.7.8, slf4j-api 2.0.16 -> 2.0.17, spring-boot 3.3.6 -> 3.5.6, spring-core 6.1.15 -> 6.2.11, swagger-inflector 2.0.12 -> 2.0.14, swagger-parser 2.1.24 -> 2.1.34)
✔️ Karate Tools - Plugins Update (central-publishing-maven-plugin 0.6.0 -> 0.9.0, jacoco-maven-plugin 0.8.12 -> 0.8.13, maven-archetype-plugin 3.3.1 -> 3.4.0, maven-enforcer-plugin 3.5.0 -> 3.6.1, maven-failsafe-plugin 3.5.2 -> 3.5.4, maven-gpg-plugin 3.2.7 -> 3.2.8, maven-javadoc-plugin 3.11.2 -> 3.12.0, maven-scm-plugin 2.1.0 -> 2.2.1, maven-surefire-plugin 3.5.2 -> 3.5.4, maven-surefire-report-plugin 3.5.2 -> 3.5.4, openapi-generator-maven-plugin 7.10.0 -> 7.12.0, pitest 1.17.3 -> 1.20.3, pitest-junit5-plugin 1.2.1 -> 1.2.3, spotbugs-maven-plugin 4.8.6.6 -> 4.9.6.0, spring-boot-maven-plugin 3.3.6 -> 3.5.6)
✔️ Karate Tools - Containers Update (mariadb 10.5.21 -> 10.11.11, postgres 15.7 -> 16.8)


| 5.0.1
| 2025-01-17
|

✔️ Karate Tools - *exec-maven-plugin Downgrade* (3.5.0 -> 3.1.0) due to console issues with MacOS. The observed issue is `Could not load library` ... `no jansi in java.library.path`

| 5.0.0
| 2025-01-14
|

✔️ Karate Tools - *Update to JDK 21*

✔️ Karate Tools - *Dependencies Update* (artemis-jms-client 2.38.0 -> 2.39.0, assertj 3.25.3 -> 3.27.2, jackson 2.18.1 -> 2.18.2, junit 5.11.3 -> 5.11.4, karate 1.4.0 -> 1.5.1, logback 1.5.12 -> 1.5.16, mariadb-java-client 3.5.0 -> 3.5.1, mockito 5.14.2 -> 5.15.2, mongodb-driver-sync 5.2.1 -> 5.3.0, slf4j 2.0.13 -> 2.0.16, spring-boot 3.3.3 -> 3.3.6, spring-core 6.1.13 -> 6.1.15)

✔️ Karate Tools - *Plugins Update* (maven-archetype-plugin 3.2.1 -> 3.3.1, maven-archetype-packaging 3.1.1 -> 3.3.1, maven-checkstyle-plugin 3.4.0 -> 3.6.0, maven-dependency-plugin 3.7.1 -> 3.8.1, maven-enforcer-plugin 3.2.1 -> 3.5.0, maven-failsafe-plugin 3.3.1 -> 3.5.2, maven-gpg-plugin 3.2.5 -> 3.2.7, maven-javadoc-plugin 3.11.1 -> 3.11.2, maven-resources-plugin 3.2.0 -> 3.3.1, maven-surefire-plugin 3.3.1 -> 3.5.2, maven-surefire-report-plugin 3.3.1 -> 3.5.2, pitest 1.16.1 -> 1.17.3, com.puppycrawl.tools.checkstyle 10.20.1 -> 10.21.1, spotbugs-maven-plugin 4.8.6.2 -> 4.8.6.6)

|===
