= Karate Tools Release Notes

[cols="1,1,6"]
|===
| Version | Date | Description

| 5.0.1
| 2025-01-17
|

✔️ Karate Tools - *exec-maven-plugin Downgrade* (3.5.0 -> 3.1.0) due to console issues with MacOS.

✔️ Karate Tools - *Added OS Compatibility Tests* (Windows, MacOS, Linux).

| 5.0.0
| 2025-01-14
|

✔️ Karate Tools - *Update to JDK 21*

✔️ Karate Tools - *Dependencies Update* (artemis-jms-client 2.38.0 -> 2.39.0, assertj 3.25.3 -> 3.27.2, jackson 2.18.1 -> 2.18.2, junit 5.11.3 -> 5.11.4, karate 1.4.0 -> 1.5.1, logback 1.5.12 -> 1.5.16, mariadb-java-client 3.5.0 -> 3.5.1, mockito 5.14.2 -> 5.15.2, mongodb-driver-sync 5.2.1 -> 5.3.0, slf4j 2.0.13 -> 2.0.16, spring-boot 3.3.3 -> 3.3.6, spring-core 6.1.13 -> 6.1.15)

✔️ Karate Tools - *Plugins Update* (maven-archetype-plugin 3.2.1 -> 3.3.1, maven-archetype-packaging 3.1.1 -> 3.3.1, maven-checkstyle-plugin 3.4.0 -> 3.6.0, maven-dependency-plugin 3.7.1 -> 3.8.1, maven-enforcer-plugin 3.2.1 -> 3.5.0, maven-failsafe-plugin 3.3.1 -> 3.5.2, maven-gpg-plugin 3.2.5 -> 3.2.7, maven-javadoc-plugin 3.11.1 -> 3.11.2, maven-resources-plugin 3.2.0 -> 3.3.1, maven-surefire-plugin 3.3.1 -> 3.5.2, maven-surefire-report-plugin 3.3.1 -> 3.5.2, pitest 1.16.1 -> 1.17.3, com.puppycrawl.tools.checkstyle 10.20.1 -> 10.21.1, spotbugs-maven-plugin 4.8.6.2 -> 4.8.6.6)

|===
