---
extends: default
rules:
  new-line-at-end-of-file:
    level: error
  trailing-spaces:
    level: error
  line-length:
    max: 140
    allow-non-breakable-words: true
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'on']
