---
self-hosted-runner:
  # Labels of self-hosted runner in array of string
  labels:
    - axecocpci1
    - pipe
    - security
    - sisifo
    - testing
    - testing-small
    - testing-medium
    - testing-x-large
    - common
    - ctm
    - apigateway
    - apis
    - byc
    - database
    - testing-ivm
    - testing-ivm-android
    - inspector
    - apirambo
    - internal
    - iac
    - icr-infra
    - platform360
    - geppetto
    - paasfeature
    - dataextension
    - ubuntu-20.04-4cores-16ram # not a self-hosted runner, however, it is a custom group of runners
    - apiapprovalprocess
    - qualitymeasuresystem
    - platformhealthchecker
    - sre
    - mlops
    - monin
    - heimdal
    - citool-icr-aks__code-ubuntu24.04-small
    - citool-icr-aks__code-ubuntu24.04-medium
    - citool-icr-aks__code-ubuntu24.04-large
    - citool-icr__code-ubuntu24.04-xsmall
    - windows-vsphere-hardening
