---
name: PR-verify

on:
  pull_request:

jobs:
  check-changes-in-paths:
    name: Check for changes in corresponding paths
    runs-on: ubuntu-20.04
    outputs:
      yaml: ${{ steps.changes.outputs.yaml }}
      yaml-files: ${{ steps.changes.outputs.yaml_files }}
      markdown: ${{ steps.changes.outputs.markdown }}
      markdown-files: ${{ steps.changes.outputs.markdown_files }}
      workflows: ${{ steps.changes.outputs.workflows }}
      workflows-files: ${{ steps.changes.outputs.workflows_files }}
    steps:
      - name: Check for changed files in specific paths
        id: changes
        uses: dorny/paths-filter@ebc4d7e9ebcb0b1eb21480bb8f43113e996ac77a
        with:
          list-files: shell
          filters: |
            yaml:
              - added|modified: '**/*.yml?(.jinja)'
              - added|modified: '**/*.yaml?(.jinja)'
            markdown:
              - added|modified: '**.md'
            workflows:
              - added|modified: '.github/workflows/*.yml'
              - added|modified: '.github/workflows/*.yaml'
              - added|modified: 'features/**/workflows/**/*.yml?(.jinja)'
              - added|modified: 'features/**/workflows/**/*.yaml?(.jinja)'

  yaml-lint:
    name: YAML Lint
    timeout-minutes: 30
    needs: check-changes-in-paths
    if: needs.check-changes-in-paths.outputs.yaml == 'true'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: YAML Lint
        run: yamllint -c .github/.yaml-lint.yml ${{ needs.check-changes-in-paths.outputs.yaml-files }}

  markdown-lint:
    name: Markdown Lint
    timeout-minutes: 30
    needs: check-changes-in-paths
    if: needs.check-changes-in-paths.outputs.markdown == 'true'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Markdown Lint
        run: npx markdownlint-cli -c .github/.markdown-lint.yml ${{ needs.check-changes-in-paths.outputs.markdown-files }}

  action-lint:
    name: Action Lint
    timeout-minutes: 30
    needs: check-changes-in-paths
    if: needs.check-changes-in-paths.outputs.workflows == 'true'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install pyflakes
        run: |
            pip install --upgrade pyflakes
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/c6bd06256dd700a45e483869bcdcf304239393a6/scripts/download-actionlint.bash) 1.6.27
      - name: Check changed workflow files
        run: |
            echo "::add-matcher::.github/actionlint-matcher.json"
            ${{ steps.get_actionlint.outputs.executable }} -ignore 'could not read reusable workflow' ${{ needs.check-changes-in-paths.outputs.workflows-files }}

  check-coding-conventions:
    name: Coding Conventions Check
    timeout-minutes: 30
    needs: check-changes-in-paths
    if: needs.check-changes-in-paths.outputs.yaml == 'true'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check Coding Conventions
        uses: ./.github/check-coding-conventions
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_READER }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        with:
          files: ${{ needs.check-changes-in-paths.outputs.yaml-files }}
